---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
    fabric8.io/iconUrl: "img/icons/vertx.svg"
  labels:
    provider: "fabric8"
    project: "piza"
    version: "v1"
    group: "zomato"
  name: "piza"
spec:
  ports:
  - port: 8778
    protocol: "TCP"
    targetPort: 8778
  selector:
    project: "piza"
    provider: "fabric8"
    group: "zomato"
  type: "LoadBalancer"
